### ISSUE TITLE
Maya freezes when pushing play in camera sequencer

### ISSUE THREAD

**Issue by solemega** [david-cattermole/cameraInferno-maya#7]
Steps to reproduce:

1.  Setup burnin
2. Open camera sequencer
3. Push play in the camera sequencer interface

Maya will freeze and will need to be killed from system task manager.
NOTE: This appears in every version of Maya 2020 I have tested so far, both on Windows and Linux.

Thank you in advance,
So

**Comment by david-cattermole** [comment]
Hello @solemega,

Thank you for reporting this!

I have tried to reproduce this on Maya 2018 and 2019, (because I do not have Maya 2020), but so far I have not been able to reproduce it in those versions.

When you open the Camera Sequencer window, do you create a new shot ("Create > Shot" menu) after this? Or is the problem happening when there are no "shots"?

I suspect the issue might be due to the Evaluation Manager and Maya's background caching.
What type of "Evaluation mode" are you using? DG or Parallel?
Are you also using background caching?

For example in the Maya preferences you can find the "Evaluation mode" here:
![image](https://user-images.githubusercontent.com/891288/104020862-c7ec1380-51b5-11eb-904d-aea5fdf9dfd0.png)

Someone else has had problems with the background caching with a Camera Inferno node; #3 

Lastly, when running in Linux and you get this freeze, can you open the terminal/shell that you used to launch Maya and then press "CTRL+C" in the terminal to cause Maya to exit? This should print out a "crash log" which will allow me to see which part of the code Maya is stuck in.
If you're able to get this crash log can you post this on this GitHub issue?

David

**Comment by sirpiltrafus** [comment]
Hi. I haven't tried your plugin yet.
But I have the same crash in Maya sequencer. Without using CameraInferno.
I have been using a version of the old Sony SpReticle plugin for in view camera display.

Just saying that I think is a Maya 2020 issue. It may be related to cameras having attached nodes or who knows what. 
Just sharing the info here in case is useful.

**Comment by solemega** [comment]
Hi @david-cattermole , thank you for your reply.
As we had an issue related to [#3 ](https://github.com/david-cattermole/cameraInferno-maya/issues/3), Maya's background caching was already deactivated.
The evaluation mode was set to "Parallel" and I confirm that when set to "DG", Maya doesn't freeze.
I guess this will work as a temporary workaround, though it is a little restrictive.

Thank you,
So
